export const HOME_URL = "/";
export const LOGIN_URL = "/login";
export const REGISTER_URL = "/register";
export const COMPLETE_URL  = '/complete'
export const PROFILE_URL = "/profile";
export const TOURS_URL = '/tours'
export const ARTDETAIL_URL='/artdetails'
export const TOURDETAILS_URL='/tourdetails'
export const RESERVATION_URL  = '/reserve'
export const ADDARTWORK_URL  = '/addartwork'
export const ARTPAGE_URL  = '/art'
export const ADDTOUR_URL = '/addtour'
